import './globals.css';
import type { Metadata } from 'next';
import { Playfair_Display, Sofia_Sans } from 'next/font/google';
import ModalProvider from './providers/modal-provider';

const playfair = Playfair_Display({ subsets: ['latin'] });
const sofia_sans = Sofia_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sofia_sans.className}>
        <ModalProvider />
        {children}
      </body>
    </html>
  );
}
